branding: false
browser_spellcheck: true
statusbar: false
menubar: false
toolbar:
  - fullscreen styleselect | bold italic underline | alignleft aligncenter alignright | forecolor backcolor | undo redo | table image link
plugins:
  - fullscreen
  - textcolor
  - table
  - image
  - link